name: Deploy to GitHub Pages
# deploys the gh-pages branch

on:
  push:
    branches:
      - master
  workflow_call:

permissions:
  pages: write
  id-token: write
  contents: read

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master

      # checkout data from json branch
      - name: Checkout json
        uses: actions/checkout@v4
        with:
          ref: json
          path: data

      # Remove once build system is configured
      - name: Copy data into site
        run: |
          cp -r data/* site/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Change to buid output directory
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy
        uses: actions/deploy-pages@v4
