name: Deploy to GitHub Pages
# deploys the gh-pages branch

on:
  workflow_call:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy
        uses: actions/deploy-pages@v4
