name: Sync Launches

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v6
        with:
          ref: master

      - name: Checkout json
        uses: actions/checkout@v6
        with:
          ref: json
          path: data

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Sync data
        run: python sync_launches.py

      - name: Commit to json if changed
        run: |
          cd data
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "Sync launches [$(date -u '+%Y-%m-%d %H:%M UTC')]"
          git push origin json

  deploy:
    needs: sync-launch
    permissions:
      pages: write
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yml
